/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;

public class Library {
    public static void main(String[] args) {

        int[] array1 = {2, 4, 6, 8};

        roll(5);
//        containsDuplicats();
//        averages(array1);
    }
    public static long[] roll(int n){

        long[] rollCount = new long[n];

        for (int i = 0; i < rollCount.length; i++){

        long x = Math.round((Math.random() * ((6 - 1) + 1)) + 1);
        rollCount[i] = x;

        }
        System.out.println(Arrays.toString(rollCount));
        return rollCount;
    }

//    public static boolean containsDuplicats(int[] arr){
//
//    };
//
//    public static int averages(int[] arr){
//
//    };


}
